---
title: "Analysis projects"
author: "Steph Locke"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analysis projects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Analysis projects are projects where you perform some analysis and probably produce some outputs. 

The function `createAnalysisProject()` aims to facilitate your analysis by setting up a best practices template project.


## Basic projects
A basic project that's created with `createBasicProject()` is the fundamental building block for this type of project. Read more about [basic projects](BasicProjects.html) to get insight into them.

## Setup
At the moment, this facility will set up a basic project with some additional folders:

- data
- analysis
- outputs

## Make your own
You could either make a wrapper around `createAnalysisProject()` to add additional setup steps, or you could make an alternative version of the function.

If you make your own, we'd be interested to hear about what you change/add and why. Please let us know on our [GitHub Issues](https://github.com/lockedata/starters/issues).
