---
title: "Basic Projects"
author: "Steph Locke"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Basic Projects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

A basic project that's created with `create_basic_project()` is the fundamental building block for various flavours of projects you might build with `starters`.

A basic project contains a minimal package structure to allow you an easy way to:

 - make functions for use within your work
 - list packages needed for easy dependency management
 - build your outputs using mechanisms aimed at packages
 
All basic projects contain:

* a DESCRIPTION file
* an `R/` directory
* an RStudio project file
* a README.Rmd. A README is a wonderful introduction to your project and it's the first thing people see when they look at it on GitHub. We will create a README.Rmd so that you can write R Markdown and produce a README.md suitable for GitHub. This enables you to show off your functions, your test results, etc. In the README created, there will be a [repostatus.org badge indicating the status of your project](https://www.repostatus.org/). By default the initial status is WIP, change it via the `initial_status` argument. 

## Optional extras
We take the opinion that your project should feature the following things by default but they can always be turned off by using the parameters in the creation of a project.

### Git
We take the stance that you should be using source control and that the source control technology you should be using is [Git](https://git-scm.com/book/en/v2/Getting-Started-Git-Basics). For the most part, we expect your Git repositories to live on [GitHub](https://github.com). To learn more about git and GitHub we recommend reading [Happy Git with R](https://happygitwithr.com/) by Jenny Bryan, the STAT 545 TAs, Jim Hester.

When the project is created all the template aspects will be committed to source control, such that you could import the project into GitHub, or use the command line to push it to GitHub.

As all the projects are created with an RStudio project, you should be able to work with the source control aspects within RStudio. You can also use your preferred shell or GUI to interact with it.

### External setup

`create_basic_project()` will by default help setting up your project on both 
GitHub (Git platform) and Travis (for continuous integration). If you want to 
opt out of those, use `external_setup = NULL`. By default, the `external_setup` argument is a named list,

```r
external_setup = list(
                     git_service = "GitHub",
                     login = gh::gh_whoami()$login,
                     private = FALSE,
                     protocol = "ssh",
                     ci_activation = "travis",
                     project_type = "basic",
                               )
```                  

#### GitHub

GitHub is the only supported Git platform at the moment. A GitHub repo of the same name as the project will be created. Its description will use the `title` 
argument of the `create_basic_project()` function. The account used will be 
the one provided as `login`, if none is provided `gh::gh_whoami()$login`. You can opt out of "ssh" in favour of "https" via the `git_protocol` element of the `external_setup` argument.

#### Travis
[Travis-CI](https://travis-ci.org/) is a free continuous integration tool that allows projects from GitHub to be checked in a clean environment and for further actions to be taken if the project doesn't have any errors. This is great for checking out your packages work, but it's also a really useful utility for analysis and training projects as you can use it to build your reproducible documentation and host it for free on GitHub.

The basic project contains a [`.travis.yml` file](https://docs.travis-ci.com/user/customizing-the-build), which holds instructions for Travis. It won't interfere in any way with your development process, and to fully enable Travis you need to [turn on Travis-CI](https://travis-ci.org/getting_started) for the package. 

[READ MORE ON TRAVIS-CI](https://docs.travis-ci.com/user/languages/r/)

### Reproducibility
A problem with programming using other people's code is that other people's code changes. This risks your results changing over time. To prevent this, there are some R packages which can help us address this.

[`packrat`](https://rstudio.github.io/packrat/) will build a manifest of package versions based on what you use at the point of production. It will then ensure people use the Packrat defined packages, instead of whatever version they have installed.

[READ MORE ON PACKRAT](https://rstudio.github.io/packrat/)

[`checkpoint`](https://rdrr.io/cran/checkpoint) moves away from using your default CRAN repository and points to a specific repository that has daily snapshots. You then work with CRAN as of a specific date (by default the date you created the project). This is lighter weight than `packrat` but does not help with non-CRAN packages.

[READ MORE ON CHECKPOINT](https://rdrr.io/cran/checkpoint)

### What else?
We're working on what else should be an optional extra for basic projects and we want your opinions. Contribute your opinion on our [GitHub Issues](https://github.com/lockedata/starters/issues).

## Make your own
We think `create_basic_project()` provides a strong foundation for creating project templates.

To use it as a base for your own internal functions, you will need to import the package and then do something like this as a function wrapper:

```{r}
create_analysis_project <- function(name,
                                  dirs = c("data", "analysis", "outputs"),
                                  ...) {
  create_basic_project(name, ...)
  createdirs(name, dirs)
  invisible(TRUE)
}

```

You can browse [`starters`' source code](https://github.com/lockedata/starters/) for inspiration.

## Camel or snake?

`create_basic_project()` (snake case) used to be named `createBasicProject()` (lower camel case). One can still use any of these names to call the function.
