---
title: "Package Projects"
author: "Steph Locke"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Package projects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The function `createPackageProject()` aims to facilitate your package development by setting up a best practices template project.

## Setup
The package projects get a basic R package structure, i.e. a DESCRIPTION file and an `R/` directory, but by default a number of [`devtools`](https://www.rstudio.com/products/rpackages/devtools/) functions are called to setup what we consider to be best practices.

Best practices include:

- Uses [`testthat`](http://r-pkgs.had.co.nz/tests.html) to unit test your code
- Using [Travis-CI](https://travis-ci.org/) for testing your package in a clean environment
- Use a code coverage platform to check how much of your code is tested by unit tests
- Licensing the package under MIT 
- Creating package documentation (README, a vignette, a package doc, and a NEWS file)
- Using git source control
- Developing the package subject to a Code of Conduct 


```{r eval=FALSE}
  devtools::use_travis(name)
  devtools::use_code_of_conduct(name)
  devtools::use_coverage(name, coverage)
  devtools::use_mit_license(name)
  use_news_md(name)
  use_package_doc(name)
  use_readme_rmd(name)
  devtools::use_testthat(name)
  devtools::use_vignette(name, name)
  devtools::use_git(pkg = name)
```


## Make your own
You could either make a wrapper around `createPackageProject()` to add additional setup steps, or you could make an alternative version of the function.

If you make your own, we'd be interested to hear about what you change/add and why. Please let us know on our [GitHub Issues](https://github.com/lockedata/pRojects/issues).
